-- Aurora DSQL と PostgreSQL の両方で動く SQL だけを使う。
-- DSQL の制約: 1文ずつ別のトランザクションで実行する。identity 列には CACHE の指定が必要。
-- インデックスは標準の CREATE INDEX で書く（DSQL に適用するときに CREATE INDEX ASYNC に置き換える）。

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
  -- Cognito のユーザー ID。開発モードでは "dev:<メールアドレス>"
  subject text NOT NULL UNIQUE,
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title text NOT NULL,
  note text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  do_date date,
  due_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS todos_user_done_do_date ON todos (user_id, done, do_date);

CREATE TABLE IF NOT EXISTS tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name text NOT NULL,
  UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS todo_tags (
  todo_id bigint NOT NULL REFERENCES todos (id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
  PRIMARY KEY (todo_id, tag_id)
);

CREATE INDEX IF NOT EXISTS todo_tags_tag ON todo_tags (tag_id);

CREATE TABLE IF NOT EXISTS api_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS api_tokens_user ON api_tokens (user_id);
