-- カレンダーアプリ（Google Calendar など）に登録する iCal フィードの URL に含めるトークン。
-- todo を読むことだけに使い、API トークン（api_tokens）とは別に発行・失効する。

CREATE TABLE IF NOT EXISTS calendar_feeds (
  id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS calendar_feeds_user ON calendar_feeds (user_id);
