/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export interface ApiTokens {
  created_at: Generated<string>;
  id: Generated<number>;
  last_used_at: string | null;
  name: string;
  revoked_at: string | null;
  token_hash: string;
  user_id: number;
}

export interface Tags {
  id: Generated<number>;
  name: string;
  user_id: number;
}

export interface Todos {
  completed_at: string | null;
  created_at: Generated<string>;
  do_date: string | null;
  done: Generated<boolean>;
  due_date: string | null;
  id: Generated<number>;
  note: Generated<string>;
  title: string;
  updated_at: Generated<string>;
  user_id: number;
}

export interface TodoTags {
  tag_id: number;
  todo_id: number;
}

export interface Users {
  created_at: Generated<string>;
  email: string;
  id: Generated<number>;
  subject: string;
}

export interface DB {
  api_tokens: ApiTokens;
  tags: Tags;
  todo_tags: TodoTags;
  todos: Todos;
  users: Users;
}
